export interface Country {
  name: string;
  flagUrl: string;
  colors: string[];
  capital: string;
}

// List of countries with their flag URLs (using Wikipedia flag images)
// and dominant colors
export const countries: Country[] = [
  { name: "United States", flagUrl: "https://upload.wikimedia.org/wikipedia/en/a/a4/Flag_of_the_United_States.svg", colors: ["#B22234", "#FFFFFF", "#3C3B6E"], capital: "Washington, D.C." },
  { name: "United Kingdom", flagUrl: "https://upload.wikimedia.org/wikipedia/en/a/ae/Flag_of_the_United_Kingdom.svg", colors: ["#012169", "#FFFFFF", "#C8102E"], capital: "London" },
  { name: "France", flagUrl: "https://upload.wikimedia.org/wikipedia/en/c/c3/Flag_of_France.svg", colors: ["#0055A4", "#FFFFFF", "#EF4135"], capital: "Paris" },
  { name: "Germany", flagUrl: "https://upload.wikimedia.org/wikipedia/en/b/ba/Flag_of_Germany.svg", colors: ["#000000", "#DD0000", "#FFCE00"], capital: "Berlin" },
  { name: "Italy", flagUrl: "https://upload.wikimedia.org/wikipedia/en/0/03/Flag_of_Italy.svg", colors: ["#009246", "#FFFFFF", "#CE2B37"], capital: "Rome" },
  { name: "Spain", flagUrl: "https://upload.wikimedia.org/wikipedia/en/9/9a/Flag_of_Spain.svg", colors: ["#AA151B", "#F1BF00", "#FFFFFF"], capital: "Madrid" },
  { name: "Canada", flagUrl: "https://upload.wikimedia.org/wikipedia/en/c/cf/Flag_of_Canada.svg", colors: ["#FF0000", "#FFFFFF"], capital: "Ottawa" },
  { name: "Japan", flagUrl: "https://upload.wikimedia.org/wikipedia/en/9/9e/Flag_of_Japan.svg", colors: ["#FFFFFF", "#BC002D"], capital: "Tokyo" },
  { name: "China", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/f/fa/Flag_of_the_People%27s_Republic_of_China.svg", colors: ["#DE2910", "#FFDE00"], capital: "Beijing" },
  { name: "India", flagUrl: "https://upload.wikimedia.org/wikipedia/en/4/41/Flag_of_India.svg", colors: ["#FF9933", "#FFFFFF", "#138808", "#000080"], capital: "New Delhi" },
  { name: "Brazil", flagUrl: "https://upload.wikimedia.org/wikipedia/en/0/05/Flag_of_Brazil.svg", colors: ["#009739", "#FEDD00", "#012169", "#FFFFFF"], capital: "Brasília" },
  { name: "Australia", flagUrl: "https://upload.wikimedia.org/wikipedia/en/b/b9/Flag_of_Australia.svg", colors: ["#00008B", "#FFFFFF", "#FF0000"], capital: "Canberra" },
  { name: "Russia", flagUrl: "https://upload.wikimedia.org/wikipedia/en/f/f3/Flag_of_Russia.svg", colors: ["#FFFFFF", "#0039A6", "#D52B1E"], capital: "Moscow" },
  { name: "Mexico", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/f/fc/Flag_of_Mexico.svg", colors: ["#006847", "#FFFFFF", "#CE1126"], capital: "Mexico City" },
  { name: "South Korea", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/0/09/Flag_of_South_Korea.svg", colors: ["#FFFFFF", "#000000", "#CE1126", "#0047A0"], capital: "Seoul" },
  { name: "Argentina", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg", colors: ["#75AADB", "#FFFFFF", "#FFC72C"], capital: "Buenos Aires" },
  { name: "Netherlands", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/2/20/Flag_of_the_Netherlands.svg", colors: ["#AE1C28", "#FFFFFF", "#21468B"], capital: "Amsterdam" },
  { name: "Sweden", flagUrl: "https://upload.wikimedia.org/wikipedia/en/4/4c/Flag_of_Sweden.svg", colors: ["#006AA7", "#FECC00"], capital: "Stockholm" },
  { name: "Norway", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Norway.svg", colors: ["#BA0C2F", "#FFFFFF", "#00205B"], capital: "Oslo" },
  { name: "Denmark", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Denmark.svg", colors: ["#C8102E", "#FFFFFF"], capital: "Copenhagen" },
  { name: "Poland", flagUrl: "https://upload.wikimedia.org/wikipedia/en/1/12/Flag_of_Poland.svg", colors: ["#FFFFFF", "#DC143C"], capital: "Warsaw" },
  { name: "Turkey", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Turkey.svg", colors: ["#E30A17", "#FFFFFF"], capital: "Ankara" },
  { name: "Greece", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Greece.svg", colors: ["#0D5EAF", "#FFFFFF"], capital: "Athens" },
  { name: "Portugal", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Portugal.svg", colors: ["#006600", "#FF0000", "#FFFF00"], capital: "Lisbon" },
  { name: "Ireland", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/4/45/Flag_of_Ireland.svg", colors: ["#169B62", "#FFFFFF", "#FF883E"], capital: "Dublin" },
  { name: "Switzerland", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f3/Flag_of_Switzerland.svg", colors: ["#FF0000", "#FFFFFF"], capital: "Bern" },
  { name: "Belgium", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Belgium.svg", colors: ["#000000", "#FAE042", "#ED2939"], capital: "Brussels" },
  { name: "Austria", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/4/41/Flag_of_Austria.svg", colors: ["#ED2939", "#FFFFFF"], capital: "Vienna" },
  { name: "Finland", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Finland.svg", colors: ["#FFFFFF", "#003580"], capital: "Helsinki" },
  { name: "Iceland", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Iceland.svg", colors: ["#02529C", "#FFFFFF", "#DC1E35"], capital: "Reykjavik" },
  { name: "New Zealand", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/3/3e/Flag_of_New_Zealand.svg", colors: ["#00008B", "#FFFFFF", "#FF0000"], capital: "Wellington" },
  { name: "South Africa", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/a/af/Flag_of_South_Africa.svg", colors: ["#000000", "#FFB612", "#007A4D", "#DE3831", "#002395", "#FFFFFF"], capital: "Cape Town" },
  { name: "Egypt", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Egypt.svg", colors: ["#CE1126", "#FFFFFF", "#000000"], capital: "Cairo" },
  { name: "Saudi Arabia", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0d/Flag_of_Saudi_Arabia.svg", colors: ["#006C35", "#FFFFFF"], capital: "Riyadh" },
  { name: "Israel", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Israel.svg", colors: ["#0038B8", "#FFFFFF"], capital: "Jerusalem" },
  { name: "Thailand", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Flag_of_Thailand.svg", colors: ["#ED1C24", "#FFFFFF", "#241D4F"], capital: "Bangkok" },
  { name: "Vietnam", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Vietnam.svg", colors: ["#DA020E", "#FFFF00"], capital: "Hanoi" },
  { name: "Indonesia", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_Indonesia.svg", colors: ["#FF0000", "#FFFFFF"], capital: "Jakarta" },
  { name: "Malaysia", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/6/66/Flag_of_Malaysia.svg", colors: ["#FF0000", "#FFFFFF", "#0000FF", "#FFCC00"], capital: "Kuala Lumpur" },
  { name: "Singapore", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Singapore.svg", colors: ["#ED2939", "#FFFFFF"], capital: "Singapore" },
  { name: "Philippines", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/9/99/Flag_of_the_Philippines.svg", colors: ["#0038A8", "#CE1126", "#FFFFFF", "#FCD116"], capital: "Manila" },
  { name: "Chile", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/7/78/Flag_of_Chile.svg", colors: ["#0039A6", "#FFFFFF", "#D52B1E"], capital: "Santiago" },
  { name: "Colombia", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Colombia.svg", colors: ["#FFCD00", "#003893", "#CE1126"], capital: "Bogotá" },
  { name: "Peru", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/c/cf/Flag_of_Peru.svg", colors: ["#D91023", "#FFFFFF"], capital: "Lima" },
  { name: "Venezuela", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/0/06/Flag_of_Venezuela.svg", colors: ["#FFCC00", "#00247D", "#CF142B"], capital: "Caracas" },
  { name: "Cuba", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/b/bd/Flag_of_Cuba.svg", colors: ["#002A8F", "#FFFFFF", "#CF142B"], capital: "Havana" },
  { name: "Jamaica", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0a/Flag_of_Jamaica.svg", colors: ["#000000", "#009639", "#FED100"], capital: "Kingston" },
  { name: "Morocco", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/2/2c/Flag_of_Morocco.svg", colors: ["#C1272D", "#006233"], capital: "Rabat" },
  { name: "Nigeria", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/7/79/Flag_of_Nigeria.svg", colors: ["#008751", "#FFFFFF"], capital: "Abuja" },
  { name: "Kenya", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Kenya.svg", colors: ["#000000", "#FFFFFF", "#DE2910", "#006600"], capital: "Nairobi" },
  { name: "Ghana", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Ghana.svg", colors: ["#CE1126", "#FCD116", "#006B3F", "#000000"], capital: "Accra" },
  { name: "Ethiopia", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/7/71/Flag_of_Ethiopia.svg", colors: ["#078930", "#FCDD09", "#DA020E", "#0F47AF"], capital: "Addis Ababa" },
  { name: "Pakistan", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/3/32/Flag_of_Pakistan.svg", colors: ["#01411C", "#FFFFFF"], capital: "Islamabad" },
  { name: "Bangladesh", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f9/Flag_of_Bangladesh.svg", colors: ["#006A4E", "#F42A41"], capital: "Dhaka" },
  { name: "Sri Lanka", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/1/11/Flag_of_Sri_Lanka.svg", colors: ["#FFBE29", "#8D1538", "#00534E", "#EB7400"], capital: "Colombo" },
  { name: "Nepal", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/9/9b/Flag_of_Nepal.svg", colors: ["#DC143C", "#0000FF", "#FFFFFF"], capital: "Kathmandu" },
  { name: "Myanmar", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8c/Flag_of_Myanmar.svg", colors: ["#FFCD00", "#34B233", "#EA2839", "#FFFFFF"], capital: "Naypyidaw" },
  { name: "Cambodia", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/8/83/Flag_of_Cambodia.svg", colors: ["#032EA1", "#E00025", "#FFFFFF"], capital: "Phnom Penh" },
  { name: "Laos", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/5/56/Flag_of_Laos.svg", colors: ["#CE1126", "#002868", "#FFFFFF"], capital: "Vientiane" },
  { name: "Mongolia", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4c/Flag_of_Mongolia.svg", colors: ["#C8102E", "#0066B2", "#FFCE00"], capital: "Ulaanbaatar" },
  { name: "Kazakhstan", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Flag_of_Kazakhstan.svg", colors: ["#00AFCA", "#FFE700", "#00AFCA"], capital: "Nur-Sultan" },
  { name: "Ukraine", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Ukraine.svg", colors: ["#0057B7", "#FFD700"], capital: "Kyiv" },
  { name: "Romania", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/7/73/Flag_of_Romania.svg", colors: ["#002B7F", "#FCD116", "#CE1126"], capital: "Bucharest" },
  { name: "Bulgaria", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Bulgaria.svg", colors: ["#FFFFFF", "#00966E", "#D62612"], capital: "Sofia" },
  { name: "Hungary", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c1/Flag_of_Hungary.svg", colors: ["#CE2939", "#FFFFFF", "#477050"], capital: "Budapest" },
  { name: "Czech Republic", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_Czech_Republic.svg", colors: ["#FFFFFF", "#D7141A", "#11457E"], capital: "Prague" },
  { name: "Slovakia", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e6/Flag_of_Slovakia.svg", colors: ["#FFFFFF", "#0B4EA2", "#EE1C25"], capital: "Bratislava" },
  { name: "Croatia", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/1/1b/Flag_of_Croatia.svg", colors: ["#171796", "#FFFFFF", "#FF0000"], capital: "Zagreb" },
  { name: "Serbia", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/f/ff/Flag_of_Serbia.svg", colors: ["#C6363C", "#FFFFFF", "#0C4076"], capital: "Belgrade" },
  { name: "Albania", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/3/36/Flag_of_Albania.svg", colors: ["#E41E20", "#000000"], capital: "Tirana" },
  { name: "Algeria", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Algeria.svg", colors: ["#FFFFFF", "#006233", "#CE1126"], capital: "Algiers" },
  { name: "Angola", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/9/9d/Flag_of_Angola.svg", colors: ["#CE1126", "#000000", "#FFCE00"], capital: "Luanda" },
  { name: "Antigua and Barbuda", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/8/89/Flag_of_Antigua_and_Barbuda.svg", colors: ["#000000", "#FFD700", "#0066FF", "#FFFFFF", "#FF0000"], capital: "St. John's" },
  { name: "Armenia", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/2/2f/Flag_of_Armenia.svg", colors: ["#D90012", "#0033A0", "#F2A800"], capital: "Yerevan" },
  { name: "Azerbaijan", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/d/dd/Flag_of_Azerbaijan.svg", colors: ["#00AFCA", "#E70013", "#009639", "#FFFFFF"], capital: "Baku" },
  { name: "Bahamas", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/9/93/Flag_of_the_Bahamas.svg", colors: ["#00ABC9", "#FFD700", "#000000"], capital: "Nassau" },
  { name: "Bahrain", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/2/2c/Flag_of_Bahrain.svg", colors: ["#FFFFFF", "#CE1126"], capital: "Manama" },
  { name: "Barbados", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/e/ef/Flag_of_Barbados.svg", colors: ["#00267F", "#FFD700", "#000000"], capital: "Bridgetown" },
  { name: "Belarus", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/8/85/Flag_of_Belarus.svg", colors: ["#D52B1E", "#006B3F", "#FFFFFF"], capital: "Minsk" },
  { name: "Belize", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e7/Flag_of_Belize.svg", colors: ["#003F87", "#CE1126", "#FFFFFF"], capital: "Belmopan" },
  { name: "Benin", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0a/Flag_of_Benin.svg", colors: ["#008751", "#FCD116", "#E8112D"], capital: "Porto-Novo" },
  { name: "Bhutan", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/9/91/Flag_of_Bhutan.svg", colors: ["#FF4E12", "#FFD700", "#FFFFFF"], capital: "Thimphu" },
  { name: "Bolivia", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Bolivia.svg", colors: ["#D52B1E", "#FFD700", "#007A33"], capital: "Sucre" },
  { name: "Bosnia and Herzegovina", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/b/bf/Flag_of_Bosnia_and_Herzegovina.svg", colors: ["#002395", "#FFD700", "#FFFFFF"], capital: "Sarajevo" },
  { name: "Botswana", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/f/fa/Flag_of_Botswana.svg", colors: ["#75AADB", "#000000", "#FFFFFF"], capital: "Gaborone" },
  { name: "Brunei", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Brunei.svg", colors: ["#FCE300", "#FFFFFF", "#000000", "#CF142B"], capital: "Bandar Seri Begawan" },
  { name: "Burkina Faso", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/3/31/Flag_of_Burkina_Faso.svg", colors: ["#EF2B2D", "#009639", "#FFD700"], capital: "Ouagadougou" },
  { name: "Burundi", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/5/50/Flag_of_Burundi.svg", colors: ["#18B637", "#000000", "#E70013", "#FFFFFF"], capital: "Gitega" },
  { name: "Cameroon", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4f/Flag_of_Cameroon.svg", colors: ["#007A5E", "#CE1126", "#FCD116", "#FFD700"], capital: "Yaoundé" },
  { name: "Cape Verde", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Cape_Verde.svg", colors: ["#003F87", "#FFFFFF", "#CE1126", "#FFD700"], capital: "Praia" },
  { name: "Central African Republic", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6f/Flag_of_the_Central_African_Republic.svg", colors: ["#003082", "#FFFFFF", "#FFCE00", "#009639", "#FF0000"], capital: "Bangui" },
  { name: "Chad", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4b/Flag_of_Chad.svg", colors: ["#002664", "#FECB00", "#C8102E"], capital: "N'Djamena" },
  { name: "Comoros", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/9/94/Flag_of_the_Comoros.svg", colors: ["#FFD700", "#FFFFFF", "#CE1126", "#009639", "#FFD700"], capital: "Moroni" },
  { name: "Congo", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/9/92/Flag_of_the_Republic_of_the_Congo.svg", colors: ["#009639", "#FBDE4A", "#CE1126"], capital: "Brazzaville" },
  { name: "Costa Rica", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Costa_Rica.svg", colors: ["#002B7F", "#FFFFFF", "#CE1126"], capital: "San José" },
  { name: "Côte d'Ivoire", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Côte_d%27Ivoire.svg", colors: ["#FFFFFF", "#F77F00", "#009639"], capital: "Yamoussoukro" },
  { name: "Cyprus", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Cyprus.svg", colors: ["#FFFFFF", "#FFCE00"], capital: "Nicosia" },
  { name: "Djibouti", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/3/34/Flag_of_Djibouti.svg", colors: ["#6AB2E7", "#12AD2B", "#FFFFFF", "#E70013"], capital: "Djibouti" },
  { name: "Dominica", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c4/Flag_of_Dominica.svg", colors: ["#006B3F", "#FFD700", "#000000", "#FFFFFF", "#E70013"], capital: "Roseau" },
  { name: "Dominican Republic", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_the_Dominican_Republic.svg", colors: ["#002D62", "#FFFFFF", "#CE1126"], capital: "Santo Domingo" },
  { name: "Ecuador", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e8/Flag_of_Ecuador.svg", colors: ["#FFD100", "#0033A0", "#CE1126"], capital: "Quito" },
  { name: "El Salvador", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/3/34/Flag_of_El_Salvador.svg", colors: ["#006847", "#FFFFFF", "#CE1126"], capital: "San Salvador" },
  { name: "Equatorial Guinea", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/3/31/Flag_of_Equatorial_Guinea.svg", colors: ["#3E9A00", "#FFFFFF", "#E70013", "#0073CF"], capital: "Malabo" },
  { name: "Eritrea", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/2/29/Flag_of_Eritrea.svg", colors: ["#3E9A00", "#FFFFFF", "#E70013", "#FFD700"], capital: "Asmara" },
  { name: "Estonia", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8f/Flag_of_Estonia.svg", colors: ["#0072CE", "#000000", "#FFFFFF"], capital: "Tallinn" },
  { name: "Eswatini", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/f/fb/Flag_of_Eswatini.svg", colors: ["#3E9A00", "#FFD700", "#000000", "#FFFFFF", "#E70013", "#0073CF"], capital: "Mbabane" },
  { name: "Fiji", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Flag_of_Fiji.svg", colors: ["#00247D", "#FFFFFF", "#E70013", "#FFD700"], capital: "Suva" },
  { name: "Gabon", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/0/04/Flag_of_Gabon.svg", colors: ["#009639", "#FFD700", "#0073CF"], capital: "Libreville" },
  { name: "Gambia", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_The_Gambia.svg", colors: ["#CE1126", "#FFFFFF", "#009639", "#00247D"], capital: "Banjul" },
  { name: "Georgia", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_Georgia.svg", colors: ["#FFFFFF", "#FF0000"], capital: "Tbilisi" },
  { name: "Guatemala", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/e/ec/Flag_of_Guatemala.svg", colors: ["#4997D0", "#FFFFFF"], capital: "Guatemala City" },
  { name: "Guinea", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/e/ed/Flag_of_Guinea.svg", colors: ["#CE1126", "#FFD700", "#009639"], capital: "Conakry" },
  { name: "Guinea-Bissau", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_Guinea-Bissau.svg", colors: ["#CE1126", "#FFD700", "#009639", "#000000"], capital: "Bissau" },
  { name: "Guyana", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/9/99/Flag_of_Guyana.svg", colors: ["#009639", "#FFFFFF", "#FFD700", "#000000", "#CE1126"], capital: "Georgetown" },
  { name: "Haiti", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/5/56/Flag_of_Haiti.svg", colors: ["#00209F", "#CE1126"], capital: "Port-au-Prince" },
  { name: "Honduras", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/8/82/Flag_of_Honduras.svg", colors: ["#0073CF", "#FFFFFF"], capital: "Tegucigalpa" },
  { name: "Iraq", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f6/Flag_of_Iraq.svg", colors: ["#CE1126", "#FFFFFF", "#000000", "#007A3D"], capital: "Baghdad" },
  { name: "Iran", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/c/ca/Flag_of_Iran.svg", colors: ["#239F40", "#FFFFFF", "#DA0000"], capital: "Tehran" },
  { name: "Jordan", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c0/Flag_of_Jordan.svg", colors: ["#000000", "#FFFFFF", "#007A3D", "#CE1126"], capital: "Amman" },
  { name: "Kuwait", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/a/aa/Flag_of_Kuwait.svg", colors: ["#007A3D", "#FFFFFF", "#000000", "#CE1126"], capital: "Kuwait City" },
  { name: "Kyrgyzstan", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c7/Flag_of_Kyrgyzstan.svg", colors: ["#FF0000", "#FFD700"], capital: "Bishkek" },
  { name: "Latvia", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/8/84/Flag_of_Latvia.svg", colors: ["#9E3039", "#FFFFFF"], capital: "Riga" },
  { name: "Lebanon", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/5/59/Flag_of_Lebanon.svg", colors: ["#ED1C24", "#FFFFFF", "#00A651"], capital: "Beirut" },
  { name: "Lesotho", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4a/Flag_of_Lesotho.svg", colors: ["#009639", "#FFFFFF", "#000000", "#CE1126"], capital: "Maseru" },
  { name: "Liberia", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b8/Flag_of_Liberia.svg", colors: ["#002868", "#FFFFFF", "#BF0A30"], capital: "Monrovia" },
  { name: "Libya", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Libya.svg", colors: ["#239F40", "#000000", "#E70013", "#FFFFFF"], capital: "Tripoli" },
  { name: "Lithuania", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/1/11/Flag_of_Lithuania.svg", colors: ["#FDB913", "#006A44", "#C8102E"], capital: "Vilnius" },
  { name: "Luxembourg", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/d/da/Flag_of_Luxembourg.svg", colors: ["#00A1DE", "#FFFFFF", "#ED2939"], capital: "Luxembourg" },
  { name: "Madagascar", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Madagascar.svg", colors: ["#FFFFFF", "#007E3A", "#E70013"], capital: "Antananarivo" },
  { name: "Malawi", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d1/Flag_of_Malawi.svg", colors: ["#000000", "#CE1126", "#009639"], capital: "Lilongwe" },
  { name: "Maldives", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_Maldives.svg", colors: ["#D21034", "#007A3D", "#FFFFFF"], capital: "Malé" },
  { name: "Mali", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/9/92/Flag_of_Mali.svg", colors: ["#14B53A", "#FCD116", "#CE1126"], capital: "Bamako" },
  { name: "Malta", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/7/73/Flag_of_Malta.svg", colors: ["#FFFFFF", "#CE1126"], capital: "Valletta" },
  { name: "Mauritania", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/4/43/Flag_of_Mauritania.svg", colors: ["#00A651", "#FFD700", "#CE1126"], capital: "Nouakchott" },
  { name: "Mauritius", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Mauritius.svg", colors: ["#EA2839", "#1A206D", "#FFD400", "#00A551"], capital: "Port Louis" },
  { name: "Moldova", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/2/27/Flag_of_Moldova.svg", colors: ["#0033A0", "#FFD700", "#CE1126"], capital: "Chișinău" },
  { name: "Monaco", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/e/ea/Flag_of_Monaco.svg", colors: ["#CE1126", "#FFFFFF"], capital: "Monaco" },
  { name: "Montenegro", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/6/64/Flag_of_Montenegro.svg", colors: ["#C8102E", "#FFD700"], capital: "Podgorica" },
  { name: "Mozambique", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d0/Flag_of_Mozambique.svg", colors: ["#009639", "#000000", "#FFD700", "#FFFFFF", "#CE1126", "#FFD700"], capital: "Maputo" },
  { name: "Namibia", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/0/00/Flag_of_Namibia.svg", colors: ["#CE1126", "#FFFFFF", "#003082", "#FFD700", "#009639"], capital: "Windhoek" },
  { name: "Niger", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f4/Flag_of_Niger.svg", colors: ["#E05206", "#FFFFFF", "#14B53A", "#FFD700"], capital: "Niamey" },
  { name: "North Macedonia", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/7/79/Flag_of_North_Macedonia.svg", colors: ["#D20000", "#FFD700"], capital: "Skopje" },
  { name: "Oman", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/d/dd/Flag_of_Oman.svg", colors: ["#FFFFFF", "#CE1126", "#009639"], capital: "Muscat" },
  { name: "Palestine", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/0/00/Flag_of_Palestine.svg", colors: ["#000000", "#FFFFFF", "#007A3D", "#CE1126"], capital: "East Jerusalem" },
  { name: "Panama", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Flag_of_Panama.svg", colors: ["#FFFFFF", "#005293", "#D21034"], capital: "Panama City" },
  { name: "Papua New Guinea", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Flag_of_Papua_New_Guinea.svg", colors: ["#000000", "#FFD700", "#CE1126"], capital: "Port Moresby" },
  { name: "Paraguay", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/2/27/Flag_of_Paraguay.svg", colors: ["#0038A8", "#FFFFFF", "#CE1126"], capital: "Asunción" },
  { name: "Qatar", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Qatar.svg", colors: ["#8B1538", "#FFFFFF"], capital: "Doha" },
  { name: "Rwanda", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/1/17/Flag_of_Rwanda.svg", colors: ["#00A1DE", "#FFD700", "#009639", "#E70013"], capital: "Kigali" },
  { name: "Saint Kitts and Nevis", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Saint_Kitts_and_Nevis.svg", colors: ["#009639", "#FFD700", "#000000", "#CE1126", "#FFFFFF"], capital: "Basseterre" },
  { name: "Saint Lucia", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_Saint_Lucia.svg", colors: ["#1EB53A", "#FFFFFF", "#FFD700", "#000000"], capital: "Castries" },
  { name: "Saint Vincent and the Grenadines", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6d/Flag_of_Saint_Vincent_and_the_Grenadines.svg", colors: ["#009639", "#FFD700", "#CE1126"], capital: "Kingstown" },
  { name: "Samoa", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/3/31/Flag_of_Samoa.svg", colors: ["#CE1126", "#00247D"], capital: "Apia" },
  { name: "San Marino", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b1/Flag_of_San_Marino.svg", colors: ["#FFFFFF", "#009639", "#CE1126"], capital: "San Marino" },
  { name: "Senegal", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/f/fd/Flag_of_Senegal.svg", colors: ["#00853F", "#FCD116", "#CE1126"], capital: "Dakar" },
  { name: "Seychelles", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/f/fc/Flag_of_Seychelles.svg", colors: ["#003D82", "#FFD700", "#CE1126", "#FFFFFF", "#009639"], capital: "Victoria" },
  { name: "Sierra Leone", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/1/17/Flag_of_Sierra_Leone.svg", colors: ["#0072CE", "#FFFFFF", "#009639"], capital: "Freetown" },
  { name: "Slovenia", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f0/Flag_of_Slovenia.svg", colors: ["#FFFFFF", "#0033A0", "#CE1126"], capital: "Ljubljana" },
  { name: "Solomon Islands", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/7/74/Flag_of_the_Solomon_Islands.svg", colors: ["#0051BA", "#FFD700", "#009639"], capital: "Honiara" },
  { name: "Somalia", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Flag_of_Somalia.svg", colors: ["#4189DD", "#FFFFFF"], capital: "Mogadishu" },
  { name: "Sudan", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_Sudan.svg", colors: ["#CE1126", "#FFFFFF", "#000000", "#009639"], capital: "Khartoum" },
  { name: "Suriname", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/6/60/Flag_of_Suriname.svg", colors: ["#377E3F", "#FFFFFF", "#CE1126", "#FFD700"], capital: "Paramaribo" },
  { name: "Syria", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/5/53/Flag_of_Syria.svg", colors: ["#CE1126", "#FFFFFF", "#000000", "#007A3D"], capital: "Damascus" },
  { name: "Tajikistan", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d0/Flag_of_Tajikistan.svg", colors: ["#006600", "#FFFFFF", "#CE1126", "#FFD700"], capital: "Dushanbe" },
  { name: "Tanzania", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Tanzania.svg", colors: ["#1EB53A", "#FFD700", "#000000", "#CE1126"], capital: "Dodoma" },
  { name: "Togo", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/6/68/Flag_of_Togo.svg", colors: ["#006A4E", "#FFD700", "#CE1126", "#FFFFFF"], capital: "Lomé" },
  { name: "Tonga", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Tonga.svg", colors: ["#CE1126", "#FFFFFF"], capital: "Nuku'alofa" },
  { name: "Trinidad and Tobago", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/6/64/Flag_of_Trinidad_and_Tobago.svg", colors: ["#CE1126", "#000000", "#FFFFFF"], capital: "Port of Spain" },
  { name: "Tunisia", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Tunisia.svg", colors: ["#E70013", "#FFFFFF", "#FFD700"], capital: "Tunis" },
  { name: "Turkmenistan", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/1/1b/Flag_of_Turkmenistan.svg", colors: ["#00843D", "#FFFFFF", "#CE1126", "#FFD700"], capital: "Ashgabat" },
  { name: "Tuvalu", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Tuvalu.svg", colors: ["#00247D", "#FFD700", "#CE1126"], capital: "Funafuti" },
  { name: "Uganda", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Flag_of_Uganda.svg", colors: ["#000000", "#FFD700", "#CE1126"], capital: "Kampala" },
  { name: "United Arab Emirates", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_United_Arab_Emirates.svg", colors: ["#FF0000", "#000000", "#FFFFFF", "#007A3D"], capital: "Abu Dhabi" },
  { name: "Uruguay", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Uruguay.svg", colors: ["#0033A0", "#FFFFFF", "#FFD700"], capital: "Montevideo" },
  { name: "Uzbekistan", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/8/84/Flag_of_Uzbekistan.svg", colors: ["#009639", "#FFFFFF", "#CE1126", "#0099FF", "#FFD700"], capital: "Tashkent" },
  { name: "Vanuatu", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Vanuatu.svg", colors: ["#FFD700", "#000000", "#CE1126", "#009639"], capital: "Port Vila" },
  { name: "Yemen", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/8/89/Flag_of_Yemen.svg", colors: ["#CE1126", "#FFFFFF", "#000000"], capital: "Sana'a" },
  { name: "Zambia", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/0/06/Flag_of_Zambia.svg", colors: ["#007A3D", "#FFD700", "#CE1126", "#000000"], capital: "Lusaka" },
  { name: "Zimbabwe", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6a/Flag_of_Zimbabwe.svg", colors: ["#009639", "#FFD700", "#CE1126", "#000000", "#FFFFFF"], capital: "Harare" },
  // US States and Territories
  { name: "Alabama", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Alabama.svg", colors: ["#FFFFFF", "#CE1126"], capital: "Montgomery" },
  { name: "Alaska", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e6/Flag_of_Alaska.svg", colors: ["#002868", "#FFD700"], capital: "Juneau" },
  { name: "Arizona", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/9/9d/Flag_of_Arizona.svg", colors: ["#CE1126", "#FFD700", "#002868", "#FFA500"], capital: "Phoenix" },
  { name: "Arkansas", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/9/9d/Flag_of_Arkansas.svg", colors: ["#CE1126", "#002868", "#FFFFFF"], capital: "Little Rock" },
  { name: "California", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_California.svg", colors: ["#FFFFFF", "#CE1126", "#002868", "#FFD700"], capital: "Sacramento" },
  { name: "Colorado", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/4/46/Flag_of_Colorado.svg", colors: ["#002868", "#FFFFFF", "#FFD700", "#CE1126"], capital: "Denver" },
  { name: "Connecticut", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/9/96/Flag_of_Connecticut.svg", colors: ["#002868", "#FFFFFF"], capital: "Hartford" },
  { name: "Delaware", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c6/Flag_of_Delaware.svg", colors: ["#002868", "#FFD700", "#CE1126"], capital: "Dover" },
  { name: "Florida", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f7/Flag_of_Florida.svg", colors: ["#CE1126", "#FFFFFF", "#002868", "#FFD700"], capital: "Tallahassee" },
  { name: "Georgia", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/5/54/Flag_of_Georgia_%28U.S._state%29.svg", colors: ["#002868", "#FFFFFF", "#CE1126", "#FFD700"], capital: "Atlanta" },
  { name: "Hawaii", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/e/ef/Flag_of_Hawaii.svg", colors: ["#002868", "#FFFFFF", "#CE1126"], capital: "Honolulu" },
  { name: "Idaho", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a4/Flag_of_Idaho.svg", colors: ["#002868", "#CE1126", "#FFD700"], capital: "Boise" },
  { name: "Illinois", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_Illinois.svg", colors: ["#FFFFFF", "#002868"], capital: "Springfield" },
  { name: "Indiana", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/a/ac/Flag_of_Indiana.svg", colors: ["#002868", "#FFD700"], capital: "Indianapolis" },
  { name: "Iowa", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/a/aa/Flag_of_Iowa.svg", colors: ["#002868", "#FFFFFF", "#CE1126"], capital: "Des Moines" },
  { name: "Kansas", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/d/da/Flag_of_Kansas.svg", colors: ["#002868", "#FFD700", "#CE1126"], capital: "Topeka" },
  { name: "Kentucky", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/8/81/Flag_of_Kentucky.svg", colors: ["#002868", "#FFFFFF"], capital: "Frankfort" },
  { name: "Louisiana", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e0/Flag_of_Louisiana.svg", colors: ["#002868", "#FFFFFF", "#CE1126"], capital: "Baton Rouge" },
  { name: "Maine", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/3/35/Flag_of_Maine.svg", colors: ["#002868", "#FFFFFF", "#CE1126", "#FFD700"], capital: "Augusta" },
  { name: "Maryland", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Flag_of_Maryland.svg", colors: ["#FFD700", "#CE1126", "#000000", "#FFFFFF"], capital: "Annapolis" },
  { name: "Massachusetts", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f2/Flag_of_Massachusetts.svg", colors: ["#002868", "#FFFFFF"], capital: "Boston" },
  { name: "Michigan", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b5/Flag_of_Michigan.svg", colors: ["#002868", "#FFFFFF", "#CE1126"], capital: "Lansing" },
  { name: "Minnesota", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/0/02/Flag_of_Minnesota.svg", colors: ["#002868", "#FFFFFF", "#CE1126"], capital: "Saint Paul" },
  { name: "Mississippi", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/4/42/Flag_of_Mississippi.svg", colors: ["#002868", "#FFFFFF", "#CE1126", "#FFD700"], capital: "Jackson" },
  { name: "Missouri", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5a/Flag_of_Missouri.svg", colors: ["#CE1126", "#FFFFFF", "#002868"], capital: "Jefferson City" },
  { name: "Montana", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_Montana.svg", colors: ["#002868", "#FFD700", "#CE1126"], capital: "Helena" },
  { name: "Nebraska", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4d/Flag_of_Nebraska.svg", colors: ["#002868", "#FFD700"], capital: "Lincoln" },
  { name: "Nevada", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f1/Flag_of_Nevada.svg", colors: ["#002868", "#FFFFFF", "#CE1126"], capital: "Carson City" },
  { name: "New Hampshire", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/2/28/Flag_of_New_Hampshire.svg", colors: ["#002868", "#FFFFFF", "#FFD700"], capital: "Concord" },
  { name: "New Jersey", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/9/92/Flag_of_New_Jersey.svg", colors: ["#FFD700", "#CE1126", "#002868"], capital: "Trenton" },
  { name: "New Mexico", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Flag_of_New_Mexico.svg", colors: ["#FFD700", "#CE1126"], capital: "Santa Fe" },
  { name: "New York", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_New_York.svg", colors: ["#002868", "#FFFFFF", "#FFD700"], capital: "Albany" },
  { name: "North Carolina", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/b/bb/Flag_of_North_Carolina.svg", colors: ["#002868", "#FFFFFF", "#CE1126"], capital: "Raleigh" },
  { name: "North Dakota", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/e/ee/Flag_of_North_Dakota.svg", colors: ["#002868", "#FFD700", "#CE1126"], capital: "Bismarck" },
  { name: "Ohio", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4c/Flag_of_Ohio.svg", colors: ["#CE1126", "#FFFFFF", "#002868"], capital: "Columbus" },
  { name: "Oklahoma", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6e/Flag_of_Oklahoma.svg", colors: ["#002868", "#FFFFFF", "#CE1126"], capital: "Oklahoma City" },
  { name: "Oregon", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b9/Flag_of_Oregon.svg", colors: ["#002868", "#FFD700"], capital: "Salem" },
  { name: "Pennsylvania", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f7/Flag_of_Pennsylvania.svg", colors: ["#002868", "#FFFFFF", "#FFD700", "#CE1126"], capital: "Harrisburg" },
  { name: "Rhode Island", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f3/Flag_of_Rhode_Island.svg", colors: ["#FFFFFF", "#CE1126", "#FFD700", "#002868"], capital: "Providence" },
  { name: "South Carolina", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/6/69/Flag_of_South_Carolina.svg", colors: ["#002868", "#FFFFFF"], capital: "Columbia" },
  { name: "South Dakota", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_South_Dakota.svg", colors: ["#002868", "#FFD700", "#CE1126"], capital: "Pierre" },
  { name: "Tennessee", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/9/9e/Flag_of_Tennessee.svg", colors: ["#CE1126", "#FFFFFF", "#002868"], capital: "Nashville" },
  { name: "Texas", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f7/Flag_of_Texas.svg", colors: ["#002868", "#FFFFFF", "#CE1126"], capital: "Austin" },
  { name: "Utah", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f6/Flag_of_Utah.svg", colors: ["#002868", "#FFFFFF", "#FFD700"], capital: "Salt Lake City" },
  { name: "Vermont", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Vermont.svg", colors: ["#002868", "#FFFFFF", "#FFD700", "#CE1126"], capital: "Montpelier" },
  { name: "Virginia", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/4/47/Flag_of_Virginia.svg", colors: ["#002868", "#FFFFFF", "#CE1126"], capital: "Richmond" },
  { name: "Washington", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/5/54/Flag_of_Washington.svg", colors: ["#002868", "#FFD700", "#FFFFFF"], capital: "Olympia" },
  { name: "West Virginia", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f8/Flag_of_West_Virginia.svg", colors: ["#FFFFFF", "#002868", "#CE1126"], capital: "Charleston" },
  { name: "Wisconsin", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/2/22/Flag_of_Wisconsin.svg", colors: ["#002868", "#FFFFFF", "#CE1126"], capital: "Madison" },
  { name: "Wyoming", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Wyoming.svg", colors: ["#002868", "#FFFFFF", "#CE1126", "#FFD700"], capital: "Cheyenne" },
  { name: "District of Columbia", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_the_District_of_Columbia.svg", colors: ["#CE1126", "#FFFFFF"], capital: "Washington, D.C." },
  { name: "American Samoa", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/8/87/Flag_of_American_Samoa.svg", colors: ["#002868", "#FFFFFF", "#CE1126", "#FFD700"], capital: "Pago Pago" },
  { name: "Guam", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/0/07/Flag_of_Guam.svg", colors: ["#CE1126", "#002868", "#FFD700"], capital: "Hagåtña" },
  { name: "Northern Mariana Islands", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e0/Flag_of_the_Northern_Mariana_Islands.svg", colors: ["#002868", "#FFFFFF", "#FFD700", "#CE1126"], capital: "Saipan" },
  { name: "Puerto Rico", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/2/28/Flag_of_Puerto_Rico.svg", colors: ["#CE1126", "#FFFFFF", "#002868"], capital: "San Juan" },
  { name: "U.S. Virgin Islands", flagUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f8/Flag_of_the_United_States_Virgin_Islands.svg", colors: ["#002868", "#FFFFFF", "#FFD700", "#CE1126"], capital: "Charlotte Amalie" },
];

